services:
  db:
    image: postgres:15
    container_name: django_db
    env_file:
      - back/.env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  back:
    build: ./back
    container_name: django_app
    ports:
      - "8000:8000"
    env_file:
      - back/.env
    depends_on:
      db:
        condition: service_healthy

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: react_app
    env_file:
      - front/.env.production
    ports:
      - "3000:80"
    depends_on:
      - back

volumes:
  postgres_data:
