services:
  db:
    image: postgres:15
    container_name: django_db
    env_file:
      - back/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  back:
    build: ./back
    container_name: django_app
    ports:
      - "8000:8000"
    env_file:
      - back/.env
    depends_on:
      - db

  front:
    build: ./front
    container_name: react_app
    env_file:
      - front/.env
    ports:
      - "3000:80"
    depends_on:
      - back

volumes:
  postgres_data:
