# Generated by Django 6.0.3 on 2026-03-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='imageUrl',
            field=models.CharField(max_length=500),
        ),
    ]
