# Generated by Django 6.0.3 on 2026-03-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
